version: '3.8'
services:
  movies:
    image: chandanasri123/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: chandanasri123/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: chandanasri123/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: chandanasri123/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

